### ISSUE TITLE
nipype workflow

### ISSUE THREAD

**Issue by maedoc** [timpx/scripts#11]
Can we convert this into a nipype workflow?

**Comment by timpx** [comment]
started to put everything in a branch. 
I'll create several workflows (surface, regions, subparcellations, mne...)
Main issue: several softs must be wrapped or finished: (mrtrix3)[https://github.com/bpinsard/nipype/tree/mrtrix3/nipype/interfaces/mrtrix3], MNE

**Comment by timpx** [comment]
Main surface should be working [now](https://github.com/timpx/scripts/tree/nipype)
