### ISSUE TITLE
Take into account two DTI runs to do correction

### ISSUE THREAD

**Issue by maedoc** [timpx/scripts#33]
Jonathan called this a "topup" correction. I have no idea what he meant, but I suppose mrtrix can take into account two images.

**Comment by timpx** [comment]
topup is the fsl function to correct the current distortion induced by head movement and eddy currents. Eddy current are already corrected in scripts using the old fsl function eddy_correct. The new function topup is better, but require a specific acquisition scheme. Last time I asked, they did not had such scheme implemented in Marseille (actually they did not bother to answer my mail). If they have improvement on their side, I will be more than happy to implement it.

**Comment by timpx** [comment]
with the  MRtrix3/mrtrix3/02ff4a8a40c8335b031ca commit and b832b1e0fb398af commit, this should now work.
Please add ```export topup="reversed``` to your config file.  The command takes a long time to run (around 12 hours)

**Comment by maedoc** [comment]
I had to restart as my oar job got cut. It seems to spend a lot of time on `Running Register`. This is normal?
