### ISSUE TITLE
FS v. SUBJECTS_DIR

### ISSUE THREAD

**Issue by maedoc** [timpx/scripts#34]
It seems that if these two environment variables do not agree, scripts does not find the results of FreeSurfer.

Why have a separate variable? I suggest either remove this from the config and expect user to set via SUBJECTS_DIR before sourcing the FreeSurfer environment or scripts should handle this itself.

**Comment by timpx** [comment]
Yes, I actually have in my config file ```export FS=$SUBJECTS_DIR```.
I use FS because it's shorter to write in the code, and to have a reminder for people to set ```$SUBJECTS_DIR```.
I'll move this from the configuration file to the main_surface with the appropriate warning if ```$SUBJECTS_DIR``` is not set.

**Comment by timpx** [comment]
see b36610e96c27ae

**Comment by maedoc** [comment]
ah cool; I ran into this because I was generating a config.sh from scratch and forgot to set `SUBJECTS_DIR` to the same value I providing for `FS` in the config.sh.

thanks
