### ISSUE TITLE
Mesh simplification produces discontinuous regions

### ISSUE THREAD

**Issue by maedoc** [timpx/scripts#46]
@dionperd and I are running a test data set, and it seems that even after correction some region is disconnected.

I was thinking that we could write a new simplification routine using CGAL, where you can track metadata on vertices (like which parcel belongs too) and when algorithm will collapse edge, you choose which metadata to keep. We can track geodesic distance to center of region on surface in order to maintain region boundaries in roughly the same place.

wdyt?

**Comment by timpx** [comment]
For CGAL, see #49.
For the bug, could you share data?

**Comment by maedoc** [comment]
it's our favorite dataset, so you already have the data!

**Comment by timpx** [comment]
solved
