### ISSUE TITLE
double check executable permissions

### ISSUE THREAD

**Issue by maedoc** [timpx/scripts#48]

**Comment by timpx** [comment]
apparently git does not retain file permission, so everything should be fine. Could you please describe again the issue @alexandracaia ?

**Comment by caiaAlexandra** [comment]
Actually I found out that is a SCP problem- it doesn't preserve file permissions. I was using it in order to copy the project from Windows machine to Fedora VM. 
(At the beginning I did not clone the project; I have downloaded it and copy it to VM.)

**Comment by maedoc** [comment]
All files on Windows are executable, it's possible your SCP defaults to copy files and set them non-executable in order to be safe.

**Comment by timpx** [comment]
ok, thanks for reporting
